// Generated by CoffeeScript 1.3.3
(function() {
  var ColorProcessor;

  ColorProcessor = function(algorithm) {
    return {
      process: function(scaledData, colorData, width, height) {
        return algorithm(scaledData, colorData, width, height);
      }
    };
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ColorProcessor;
  }

}).call(this);
