// Generated by CoffeeScript 1.3.3
(function() {
  var colors;

  colors = {
    grayscale: function(scaleData, colorData) {
      var i, value, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = scaleData.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        value = scaleData[i];
        _results.push(colorData[i] = (255 << 24) | (value << 16) | (value << 8) | value);
      }
      return _results;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = colors;
  }

}).call(this);
