// Generated by CoffeeScript 1.3.3
(function() {
  var colors;

  colors = {
    grayscale: function(scaledData, colorData, width, height) {}
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = colors;
  }

}).call(this);
