// Generated by CoffeeScript 1.3.3
(function() {
  var ColorProcessor;

  ColorProcessor = function(algorithm) {
    return {
      process: function() {
        return algorithm;
      }
    };
  };

}).call(this);
