// Generated by CoffeeScript 1.3.3
(function() {
  var ScaleProcessor;

  ScaleProcessor = function(algorithm) {
    return {
      process: function(fitsData, scaleData, min, max, width, height) {
        return algorithm(fitsData, scaleData, min, max, width, height);
      }
    };
  };

}).call(this);
