// Generated by CoffeeScript 1.3.3
(function() {
  var linear, scales;

  scales = {
    linear: linear = function(fitsData, scaleData, min, max, width, height) {
      var index, range, x, y, _i, _ref, _results;
      range = max - min;
      index = 0;
      _results = [];
      for (x = _i = 0, _ref = width - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (y = _j = 0, _ref1 = height - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
            index = y * width + x;
            _results1.push(scaleData[index] = ~~(255 * ((fitsData[index] - min) / range)));
          }
          return _results1;
        })());
      }
      return _results;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = scales;
  }

}).call(this);
