// Generated by CoffeeScript 1.3.3
(function() {
  var linear, scales;

  scales = {
    linear: linear = function(fitsData, scaleData, min, max) {
      var i, index, range, _i, _ref, _results;
      range = max - min;
      index = 0;
      _results = [];
      for (i = _i = 0, _ref = scaleData.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push(scaleData[i] = ~~(255 * ((fitsData[i] - min) / range)));
      }
      return _results;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = scales;
  }

}).call(this);
