// Generated by CoffeeScript 1.3.3
(function() {
  var ScaleProcessor;

  ScaleProcessor = function(algorithm) {
    this.algorithm = algorithm;
    return {
      process: function(fitsData, scaleData, min, max, width, height) {
        return this.algorithm(fitsData, scaleData, min, max, width, height);
      }
    };
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ScaleProcessor;
  }

}).call(this);
