// Generated by CoffeeScript 1.3.3
(function() {
  var Image;

  Image = (function() {

    function Image() {}

    return Image;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Image;
  }

}).call(this);
