// Generated by CoffeeScript 1.3.3
(function() {
  var Image;

  Image = (function() {

    function Image() {}

    Image.prototype.contructor = function(width, height) {
      this.width = width;
      this.height = height;
    };

    return Image;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Image;
  }

}).call(this);
